- name: Install terraform And Initialize
  on: [push]
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  job:
    name: 'Terraform'
    runs-on: self-hosted
  steps:
    - uses: actions/checkout@v2
    - name: Checkout 
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply --auto-approve
