name: Install Terraform And Initialize

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: src
         
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
     
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
              terraform_version: latest

      - name: Terraform Destroy
        if: github.ref == 'refs/heads/main'
        run: terraform destroy --auto-approve
